name: mpm-lecture
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy>=2.1
  - matplotlib>=3.10
  - pip:
      # THE BELOW ONE IS NOT A REQUIRED LINE. - -e should fetch everything from requirements.txt but some people were facing an issue
      # You can just avoid using a requirements.txt and just add all dependencies here Ig - CONFIRM THIS
      - -r requirements.txt 
      - -e . # install local repo
